
- type: replace
  path: /instance_groups/name=loghost/jobs/-
  value:
    name: bpm
    release: bpm

- type: replace
  path: /instance_groups/name=loghost/jobs/-
  value:
    name: loghost_exporter
    release: loghost
    properties:
      loghost_exporter:
          metrics:
            - name: loghost_error_total
              type: counter
              help: number of errors logs
              match: '(level=error|level":"error|Subscribe error|lvl=err|lvl=eror)'
              scope: local
              labels: &labels
                #                            base  dir   dep   grp
                director:   '{{gsub .logfile "/var/vcap/store/loghost/(.*?)/(.*?)/(.*?)\\.log" "\\1"}}'
                deployment: '{{gsub .logfile "/var/vcap/store/loghost/(.*?)/(.*?)/(.*?)\\.log" "\\2"}}'
                group:      '{{gsub .logfile "/var/vcap/store/loghost/(.*?)/(.*?)/(.*?)\\.log" "\\3"}}'
            - name: loghost_total
              type: counter
              help: number of logs
              match: '.*'
              scope: global
              labels:
                <<: *labels
          local-directors:
            - ((director_name))
          remote-directors: []

- type: replace
  path: /releases/name=bpm?
  value:
    name: bpm
    version: latest
