- type: replace
  path: /instance_groups/-
  value:
    instances: 1
    azs: [z1]
    name: loghost
    jobs:
      - name: loghost_concentrator
        release: loghost
        properties:
          loghost_concentrator:
            syslog:
              tcp:
                enabled: false
                port: 514
              udp:
                enabled: true
                port: 514
              forward: {}
              longterm-jobs:
                - deployment: cf
                  job: api
                - deployment: cf
                  job: uaa
            logrotate:
              default-max-hours: 360
              longterm-max-hours: 1440
    networks:
      - name: default
    stemcell: default
    vm_type: default
    persistent_disk_type: 10GB

# release
- type: replace
  path: /releases/-
  value:
    name: loghost
    version: "((loghost.version))"
    url: https://github.com/orange-cloudfoundry/loghost-boshrelease/releases/download/v((loghost.version))/loghost-((loghost.version)).tgz
