- type: replace
  path: /instance_groups/name=loghost/jobs/name=loghost_concentrator/properties/loghost_concentrator/syslog/tcp/enabled?
  value: true

- type: replace
  path: /instance_groups/name=loghost/jobs/name=loghost_concentrator/properties/loghost_concentrator/syslog/tcp/port?
  value: 6514

- type: replace
  path: /instance_groups/name=loghost/jobs/name=loghost_concentrator/properties/loghost_concentrator/syslog/tls?
  value:
    cert: ((loghost_ssl.certificate))
    ca: ((loghost_ssl.ca))
    key: ((loghost_ssl.private_key))
