{
 "title": "Overview",
 "tags": [ "logs" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "director",
    "query": {
     "query": "label_values(loghost_total, director)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(loghost_total{director=~\"$director\"}, deployment)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(loghost_total{director=~\"$director\", deployment=~\"$deployment\"}, group)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log processing",
   "type": "stat",
   "description": "Shows if logs are correctly processed",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(increase(loghost_total{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}[15m]))) or vector(0)"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "stat",
   "description": "Show disk utilization",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bosh_job_persistent_disk_percent{bosh_job_name=\"loghost\"}"
    }
   ]
  },
  {
   "title": "Total log/s",
   "type": "stat",
   "description": "Show current total number of processed logs per seconds",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(loghost_total{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}[10m]))"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "current loghost_exporter version",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "grok_exporter_build_info" }
   ]
  },
  {
   "title": "Components",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "description": "Show the number of logs flagged as *error* for each component",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(loghost_error_total{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}[15m])",
     "legendFormat": "{{director}} / {{deployment}} / {{group}}"
    }
   ]
  },
  {
   "title": "Log rate",
   "type": "graph",
   "description": "Show the number of logs flagged as *error* for each component",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(loghost_total{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}[15m])",
     "legendFormat": "{{director}} / {{deployment}} / {{group}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "piechart",
   "description": "Show the number of logs flagged as *error* for each component",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loghost_error_total{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}[15m]",
     "legendFormat": "{{director}} / {{deployment}} / {{group}}"
    }
   ]
  },
  {
   "title": "Log rate",
   "type": "piechart",
   "description": "Show the number of logs flagged as *error* for each component",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loghost_total{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}[15m]",
     "legendFormat": "{{director}} / {{deployment}} / {{group}}"
    }
   ]
  },
  {
   "title": "Rules processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sucess rate",
   "type": "graph",
   "description": "Show the number of matching log lines per second for each defined rule",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(grok_exporter_lines_matching_total[15m])",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Process error rate",
   "type": "graph",
   "description": "Show the number of **processing** errors per second for each defined rule. Is not not the number of logs reporting a component error.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(grok_exporter_line_processing_errors_total[15m])",
     "legendFormat": "{{metric}}"
    }
   ]
  }
 ]
}