{
 "title": "Security",
 "tags": [
  "logs",
  "security"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "director",
    "query": "label_values(loghost_total, director)"
   },
   {
    "name": "deployment",
    "query": "label_values(loghost_total{director=~\"$director\"}, deployment)"
   },
   {
    "name": "group",
    "query": "label_values(loghost_total{director=~\"$director\", deployment=~\"$deployment\"}, group)"
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log processing",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=\"LoghostNoLogReceived\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Security",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(ALERTS{alertname=~\"Security.*\"}) or vector(0)"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Failures / 5m",
   "type": "graph",
   "description": "Shows the increase of authentication failures in the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loghost_auth_failures_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (source, ip) > 0",
     "legendFormat": "source={{source}}, ip={{ip}} "
    }
   ]
  },
  {
   "title": "Success / 5m",
   "type": "graph",
   "description": "Shows the increase of authentication success in the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loghost_auth_success_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (source, username, ip) > 0",
     "legendFormat": "source={{source}}, username={{username}}, ip={{ip}} "
    }
   ]
  },
  {
   "title": "Current failure distribution per target",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication failure per target",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_auth_failures_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (director, deployment, group) > 0",
     "legendFormat": "{{deployment}}/{{group}}"
    }
   ]
  },
  {
   "title": "Current failure distribution per origin",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication failure per origin",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_auth_failures_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (ip) > 0",
     "legendFormat": "ip={{ip}}"
    }
   ]
  },
  {
   "title": "Current success distribution per target",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication success per target",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_auth_success_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (director, deployment, group) > 0",
     "legendFormat": "{{deployment}}/{{group}}"
    }
   ]
  },
  {
   "title": "Current success distribution per origin",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication success per origin",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_auth_success_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (ip) > 0",
     "legendFormat": "ip={{ip}}"
    }
   ]
  },
  { "title": "UAA (User)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Failures / 5m",
   "type": "graph",
   "description": "Shows the increase of authentication failures in the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loghost_uaa_user_login_failure_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (ip) > 0",
     "legendFormat": "ip={{ip}} "
    }
   ]
  },
  {
   "title": "Success / 5m",
   "type": "graph",
   "description": "Shows the increase of authentication success in the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loghost_uaa_user_login_success_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (username, ip) > 0",
     "legendFormat": "username={{username}}, ip={{ip}} "
    }
   ]
  },
  {
   "title": "Current failure distribution per origin",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication failure per origin",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_uaa_user_login_failure_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (ip) > 0",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Current failure distribution per target",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication failure per target",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_uaa_user_login_failure_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (director, deployment, group) > 0",
     "legendFormat": "{{deployment}}/{{group}}"
    }
   ]
  },
  {
   "title": "Current success distribution per target",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication success per target",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_uaa_user_login_success_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (director, deployment, group) > 0",
     "legendFormat": "{{deployment}}/{{group}}"
    }
   ]
  },
  {
   "title": "Current success distribution per origin",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication success per origin",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_uaa_user_login_success_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (clientid, ip) > 0",
     "legendFormat": "clientid={{clientid}}, ip={{ip}}"
    }
   ]
  },
  { "title": "UAA (Clients)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Failures / 5m",
   "type": "graph",
   "description": "Shows the increase of authentication failures in the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loghost_uaa_client_login_failure_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (ip) > 0",
     "legendFormat": "ip={{ip}} "
    }
   ]
  },
  {
   "title": "Success / 5m",
   "type": "graph",
   "description": "Shows the increase of authentication success in the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(loghost_uaa_client_login_success_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (clientid, ip) > 0",
     "legendFormat": "clientid={{clientid}}, ip={{ip}} "
    }
   ]
  },
  {
   "title": "Current failure distribution per origin",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication failure per origin",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_uaa_client_login_failure_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (ip) > 0",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Current failure distribution per target",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication failure per target",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 41 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_uaa_client_login_failure_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (director, deployment, group) > 0",
     "legendFormat": "{{deployment}}/{{group}}"
    }
   ]
  },
  {
   "title": "Current success distribution per target",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication success per target",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 41 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_uaa_client_login_success_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (director, deployment, group) > 0",
     "legendFormat": "{{deployment}}/{{group}}"
    }
   ]
  },
  {
   "title": "Current success distribution per origin",
   "type": "grafana-piechart-panel",
   "description": "Show the distribution of current authentication success per origin",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 41 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(loghost_uaa_client_login_success_last_5m{director=~\"$director\", deployment=~\"$deployment\", group=~\"$group\"}) by (clientid, ip) > 0",
     "legendFormat": "clientid={{clientid}}, ip={{ip}}"
    }
   ]
  }
 ]
}